#!/usr/bin/env python

import rospy
from nav_msgs.msg import Path
from geometry_msgs.msg import PoseStamped
from nav_msgs.msg import Odometry

class PathPublisher:
    def __init__(self):
        rospy.init_node('path_publisher')
        self.path_pub = rospy.Publisher('/path', Path, queue_size=10)
        self.path_msg = Path()
        self.path_msg.header.frame_id = "world"
        rospy.Subscriber('/hummingbird/ground_truth/odometry', Odometry, self.odom_callback)

    def odom_callback(self, msg):
        pose = PoseStamped()
        pose.header = msg.header
        pose.header.frame_id = "world"
        pose.pose = msg.pose.pose
        self.path_msg.header.stamp = rospy.Time.now()
        self.path_msg.poses.append(pose)
        self.path_pub.publish(self.path_msg)

    def run(self):
        rospy.spin()

if __name__ == '__main__':
    try:
        PathPublisher().run()
    except rospy.ROSInterruptException:
        pass

